### ISSUE TITLE
Psycopg2 cursor being closed in runtime after some time

### ISSUE THREAD

**Issue by IanGlass** [IanGlass/Jira-Helper#14]
Exception in thread Thread-18011:
Traceback (most recent call last):
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Ian\Documents\Projects\Jira-Helper\source\analytics.py", line 139, in update_analytics
    self.ticket_history = database.fetch_ticket_history()
  File "C:\Users\Ian\Documents\Projects\Jira-Helper\source\database.py", line 65, in fetch_ticket_history
    self.cur.execute('select stamp, support, customer, in_progress, dev, design, test from ticket_history where stamp > now() - %(period)s::interval', {"period": DISPLAY_PERIOD})
psycopg2.InterfaceError: cursor already closed

**Comment by IanGlass** [comment]
Deprecated, using SQLAlchemy now
